// src/utils/mockData.js

import p1 from "../assets/projects/1.jpg";
import p2 from "../assets/projects/2Portfolio.jpg";
import p3 from "../assets/projects/3.jpg";
import p4 from "../assets/projects/4.jpg";
import p5 from "../assets/projects/5.jpg";
import p6 from "../assets/projects/6.jpg";
import p7 from "../assets/projects/7.jpg";
import p8 from "../assets/projects/8.jpg";
import p9 from "../assets/projects/9.jpg";
import p10 from "../assets/projects/10.jpg";
import p11 from "../assets/projects/11.jpg";
import p12 from "../assets/projects/12.jpg";
import p13 from "../assets/projects/13.jpg";
import p14 from "../assets/projects/14.jpg";
import p15 from "../assets/projects/15.jpg";
import p16 from "../assets/projects/16.jpg";
import p17 from "../assets/projects/17.jpg";
import p18 from "../assets/projects/18.jpg";

import mockTalents from "../data/mockTalents";

export const projects = [
  {
    id: "p1",
    title: "Brand Identity for EcoKart",
    category: "Branding",
    budget: 5000,
    experienceLevel: "Intermediate",
    projectType: "Fixed",
    duration: "2-3 weeks",
    deadline: "2025-02-15",
    datePosted: "2025-01-12",
    skillsRequired: ["Logo Design", "Brand Strategy", "Illustrator"],
    proposalsCount: 12,
    location: "Remote",
    image: p1,
<<<<<<< HEAD
    shortDescription:
      "Complete branding package including logo and marketing visuals.",
    fullDescription:
      "Looking for a designer to create a cohesive brand identity including logo, typography, color system and promotional materials.",
    postedBy: {
      id: "c1",
      name: "Riya Sharma",
      role: "Startup Founder",
      rating: 4.8,
    },
  },

=======
    shortDescription: "Complete branding package including logo and marketing visuals.",
    fullDescription: "Looking for a designer to create a cohesive brand identity including logo, typography, color system and promotional materials.",
    postedBy: { id: "c1", name: "Riya Sharma", role: "Startup Founder", rating: 4.8 }
  },
>>>>>>> a91243805d08f328402fd2e4be2d22368deee673
  {
    id: "p2",
    title: "Portfolio Website for Developer",
    category: "Web Development",
    budget: 8000,
    experienceLevel: "Beginner",
    projectType: "Fixed",
    duration: "1-2 weeks",
    deadline: "2025-02-10",
    datePosted: "2025-01-05",
    skillsRequired: ["React", "Tailwind", "Responsive Design"],
    proposalsCount: 18,
    location: "Remote",
    image: p2,
    shortDescription: "Modern personal portfolio website.",
<<<<<<< HEAD
    fullDescription:
      "Need a clean and responsive portfolio site to showcase projects, resume and contact form.",
    postedBy: {
      id: "c2",
      name: "Arjun Mehta",
      role: "CS Student",
      rating: 4.5,
    },
  },
  {
      id: "p3",
      title: "Cafe Menu Redesign",
      category: "Graphic Design",
      budget: 2500,
      experienceLevel: "Beginner",
      projectType: "Fixed",
      duration: "1 week",
      deadline: "2025-02-05",
      datePosted: "2025-01-20",
      skillsRequired: ["Photoshop", "Typography", "Print Design"],
      proposalsCount: 7,
      location: "On-site",
      image: p3,
      shortDescription: "Fresh and aesthetic redesign of cafe menu.",
      fullDescription: "Seeking a designer to revamp our cafe menu layout with modern typography and clean visuals.",
      postedBy: { id: "c3", name: "Urban Brew", role: "Cafe Owner", rating: 4.3 }
    },
    {
      id: "p4",
      title: "Mobile App for Food Delivery",
      category: "App Design",
      budget: 12000,
      experienceLevel: "Expert",
      projectType: "Fixed",
      duration: "3-4 weeks",
      deadline: "2025-02-28",
      datePosted: "2025-01-02",
      skillsRequired: ["Figma", "UX Research", "Mobile UI"],
      proposalsCount: 9,
      location: "Hybrid",
      image: p4,
      shortDescription: "Complete UI/UX redesign for food delivery app.",
      fullDescription: "Redesigning a campus food delivery mobile app to improve usability and ordering experience.",
      postedBy: { id: "c4", name: "CampusEats", role: "Startup Team", rating: 4.9 }
    },
    {
      id: "p5",
      title: "YouTube Intro Animation",
      category: "Motion Design",
      budget: 1800,
      experienceLevel: "Beginner",
      projectType: "Fixed",
      duration: "5 days",
      deadline: "2025-02-08",
      datePosted: "2025-01-18",
      skillsRequired: ["After Effects", "Animation"],
      proposalsCount: 15,
      location: "Remote",
      image: p5,
      shortDescription: "5-second animated intro for YouTube channel.",
      fullDescription: "Need a catchy intro animation with logo reveal and sound effects.",
      postedBy: { id: "c5", name: "TechWithSam", role: "Content Creator", rating: 4.6 }
    },
    {
      id: "p6",
      title: "Poster Series for Tech Fest",
      category: "Graphic Design",
      budget: 4000,
      experienceLevel: "Intermediate",
      projectType: "Fixed",
      duration: "2 weeks",
      deadline: "2025-02-12",
      datePosted: "2025-01-10",
      skillsRequired: ["Illustrator", "Poster Design"],
      proposalsCount: 10,
      location: "On-site",
      image: p6,
      shortDescription: "Vibrant poster designs for college tech fest.",
      fullDescription: "Design a series of bold posters for an annual college technology festival.",
      postedBy: { id: "c6", name: "TechFest Committee", role: "Event Organizer", rating: 4.4 }
    },
    {
      id: "p7",
      title: "Landing Page for Startup",
      category: "Web Design",
      budget: 7000,
      experienceLevel: "Intermediate",
      projectType: "Fixed",
      duration: "2 weeks",
      deadline: "2025-02-20",
      datePosted: "2025-01-25",
      skillsRequired: ["UI/UX", "SEO"],
      proposalsCount: 14,
      location: "Remote",
      image: p7,
      shortDescription: "Conversion-focused startup landing page.",
      fullDescription: "Create a visually strong landing page optimized for user engagement and sign-ups.",
      postedBy: { id: "c7", name: "NextWave Labs", role: "Tech Startup", rating: 4.7 }
    },
    {
      id: "p8",
      title: "3D Mascot for App",
      category: "3D Design",
      budget: 9500,
      experienceLevel: "Expert",
      projectType: "Fixed",
      duration: "3 weeks",
      deadline: "2025-03-05",
      datePosted: "2025-01-08",
      skillsRequired: ["Blender", "3D Modeling"],
      proposalsCount: 6,
      location: "Remote",
      image: p8,
      shortDescription: "Custom 3D mascot character design.",
      fullDescription: "Design a unique and expressive 3D mascot for branding and marketing use.",
      postedBy: { id: "c8", name: "Appify", role: "Product Team", rating: 4.8 }
    },
    {
      id: "p9",
      title: "Social Media Ad Creatives",
      category: "Marketing Design",
      budget: 3200,
      experienceLevel: "Beginner",
      projectType: "Fixed",
      duration: "1 week",
      deadline: "2025-02-14",
      datePosted: "2025-01-15",
      skillsRequired: ["Canva", "Photoshop"],
      proposalsCount: 20,
      location: "Remote",
      image: p9,
      shortDescription: "Scroll-stopping Instagram ad creatives.",
      fullDescription: "Design engaging ad creatives for social campaigns targeting Gen-Z audience.",
      postedBy: { id: "c9", name: "Glow Beauty", role: "Marketing Manager", rating: 4.5 }
    },
    {
      id: "p10",
      title: "E-commerce Product Gallery",
      category: "Web Development",
      budget: 6500,
      experienceLevel: "Intermediate",
      projectType: "Hourly",
      duration: "2 weeks",
      deadline: "2025-02-18",
      datePosted: "2025-01-14",
      skillsRequired: ["JavaScript", "React"],
      proposalsCount: 11,
      location: "Remote",
      image: p10,
      shortDescription: "Interactive product gallery system.",
      fullDescription: "Build a dynamic product gallery with zoom, filters and quick preview features.",
      postedBy: { id: "c10", name: "StyleCart", role: "E-commerce Brand", rating: 4.6 }
    },
    {
      id: "p11",
      title: "Brand Guidelines Document",
      category: "Branding",
      budget: 2800,
      experienceLevel: "Intermediate",
      projectType: "Fixed",
      duration: "10 days",
      deadline: "2025-02-22",
      datePosted: "2025-01-22",
      skillsRequired: ["Brand Strategy", "Documentation"],
      proposalsCount: 5,
      location: "Remote",
      image: p11,
      shortDescription: "Detailed brand guidelines PDF.",
      fullDescription: "Prepare a professional brand guidelines document covering logo usage, fonts and colors.",
      postedBy: { id: "c11", name: "LaunchPad", role: "Startup Founder", rating: 4.4 }
    },
    {
      id: "p12",
      title: "Animated Logo for Tech Startup",
      category: "Motion Design",
      budget: 4500,
      experienceLevel: "Intermediate",
      projectType: "Fixed",
      duration: "1 week",
      deadline: "2025-02-25",
      datePosted: "2025-01-30",
      skillsRequired: ["After Effects", "Motion Graphics"],
      proposalsCount: 8,
      location: "Remote",
      image: p12,
      shortDescription: "Smooth animated logo reveal.",
      fullDescription: "Create a dynamic animated logo intro for website and promotional videos.",
      postedBy: { id: "c12", name: "CodeNova", role: "Tech Startup", rating: 4.7 }
    },
    {
      id: "p13",
      title: "Mobile App Icon Set",
      category: "App Design",
      budget: 3800,
      experienceLevel: "Beginner",
      projectType: "Fixed",
      duration: "1 week",
      deadline: "2025-02-27",
      datePosted: "2025-01-28",
      skillsRequired: ["Figma", "Icon Design"],
      proposalsCount: 13,
      location: "Remote",
      image: p13,
      shortDescription: "Custom icon set for productivity app.",
      fullDescription: "Design cohesive and minimal app icon pack following modern UI standards.",
      postedBy: { id: "c13", name: "FocusFlow", role: "App Founder", rating: 4.5 }
    },
    {
      id: "p14",
      title: "Print Ad Campaign Design",
      category: "Marketing Design",
      budget: 7500,
      experienceLevel: "Expert",
      projectType: "Fixed",
      duration: "3 weeks",
      deadline: "2025-03-10",
      datePosted: "2025-01-31",
      skillsRequired: ["Campaign Design", "Print Media"],
      proposalsCount: 4,
      location: "On-site",
      image: p14,
      shortDescription: "Complete print campaign visuals.",
      fullDescription: "Develop a strong visual campaign for lifestyle brand across newspapers and billboards.",
      postedBy: { id: "c14", name: "UrbanLife", role: "Marketing Head", rating: 4.9 }
    },
    {
      id: "p15",
      title: "Digital Art Series",
      category: "Digital Art",
      budget: 4899,
      experienceLevel: "Intermediate",
      projectType: "Fixed",
      duration: "2 weeks",
      deadline: "2025-03-15",
      datePosted: "2025-03-03",
      skillsRequired: ["Procreate", "Illustration"],
      proposalsCount: 6,
      location: "Remote",
      image: p15,
      shortDescription: "Original digital art collection.",
      fullDescription: "Create a themed digital art series for an upcoming online exhibition.",
      postedBy: { id: "c15", name: "ArtSphere", role: "Gallery Curator", rating: 4.6 }
    },
    {
      id: "p16",
      title: "Corporate Identity Package",
      category: "Branding",
      budget: 9999,
      experienceLevel: "Expert",
      projectType: "Fixed",
      duration: "4 weeks",
      deadline: "2025-03-25",
      datePosted: "2025-03-07",
      skillsRequired: ["Brand Identity", "Visual Systems"],
      proposalsCount: 3,
      location: "Hybrid",
      image: p16,
      shortDescription: "Full corporate identity development.",
      fullDescription: "Develop logo, stationery, brand book and corporate communication templates.",
      postedBy: { id: "c16", name: "PrimeCorp", role: "Corporate Client", rating: 4.8 }
    },
    {
      id: "p17",
      title: "Website Redesign for E-commerce Store",
      category: "Web Development",
      budget: 8799,
      experienceLevel: "Intermediate",
      projectType: "Fixed",
      duration: "3 weeks",
      deadline: "2025-03-28",
      datePosted: "2025-03-09",
      skillsRequired: ["React", "UX Optimization"],
      proposalsCount: 10,
      location: "Remote",
      image: p17,
      shortDescription: "Modern redesign of online fashion store.",
      fullDescription: "Redesign website UI to improve user flow, checkout experience and performance.",
      postedBy: { id: "c17", name: "FashionHub", role: "Store Owner", rating: 4.7 }
    },
    {
      id: "p18",
      title: "Product Photography Session",
      category: "Photography",
      budget: 6799,
      experienceLevel: "Intermediate",
      projectType: "Fixed",
      duration: "1 week",
      deadline: "2025-03-18",
      datePosted: "2025-03-04",
      skillsRequired: ["Product Photography", "Lighting"],
      proposalsCount: 5,
      location: "On-site",
      image: p18,
      shortDescription: "Professional product shoot.",
      fullDescription: "Capture high-quality product images for marketing and website use.",
      postedBy: { id: "c18", name: "TechNova", role: "Startup Founder", rating: 4.6 }
    }

  // keep the rest of your projects exactly the same (p3 → p18)
];

export const profiles = mockTalents;

export const getAllProjects = () => {
  return projects;
};
=======
    fullDescription: "Need a clean and responsive portfolio site to showcase projects, resume and contact form.",
    postedBy: { id: "c2", name: "Arjun Mehta", role: "CS Student", rating: 4.5 }
  },
  {
    id: "p3",
    title: "Cafe Menu Redesign",
    category: "Graphic Design",
    budget: 2500,
    experienceLevel: "Beginner",
    projectType: "Fixed",
    duration: "1 week",
    deadline: "2025-02-05",
    datePosted: "2025-01-20",
    skillsRequired: ["Photoshop", "Typography", "Print Design"],
    proposalsCount: 7,
    location: "On-site",
    image: p3,
    shortDescription: "Fresh and aesthetic redesign of cafe menu.",
    fullDescription: "Seeking a designer to revamp our cafe menu layout with modern typography and clean visuals.",
    postedBy: { id: "c3", name: "Urban Brew", role: "Cafe Owner", rating: 4.3 }
  },
  {
    id: "p4",
    title: "Mobile App for Food Delivery",
    category: "App Design",
    budget: 12000,
    experienceLevel: "Expert",
    projectType: "Fixed",
    duration: "3-4 weeks",
    deadline: "2025-02-28",
    datePosted: "2025-01-02",
    skillsRequired: ["Figma", "UX Research", "Mobile UI"],
    proposalsCount: 9,
    location: "Hybrid",
    image: p4,
    shortDescription: "Complete UI/UX redesign for food delivery app.",
    fullDescription: "Redesigning a campus food delivery mobile app to improve usability and ordering experience.",
    postedBy: { id: "c4", name: "CampusEats", role: "Startup Team", rating: 4.9 }
  },
  {
    id: "p5",
    title: "YouTube Intro Animation",
    category: "Motion Design",
    budget: 1800,
    experienceLevel: "Beginner",
    projectType: "Fixed",
    duration: "5 days",
    deadline: "2025-02-08",
    datePosted: "2025-01-18",
    skillsRequired: ["After Effects", "Animation"],
    proposalsCount: 15,
    location: "Remote",
    image: p5,
    shortDescription: "5-second animated intro for YouTube channel.",
    fullDescription: "Need a catchy intro animation with logo reveal and sound effects.",
    postedBy: { id: "c5", name: "TechWithSam", role: "Content Creator", rating: 4.6 }
  },
  {
    id: "p6",
    title: "Poster Series for Tech Fest",
    category: "Graphic Design",
    budget: 4000,
    experienceLevel: "Intermediate",
    projectType: "Fixed",
    duration: "2 weeks",
    deadline: "2025-02-12",
    datePosted: "2025-01-10",
    skillsRequired: ["Illustrator", "Poster Design"],
    proposalsCount: 10,
    location: "On-site",
    image: p6,
    shortDescription: "Vibrant poster designs for college tech fest.",
    fullDescription: "Design a series of bold posters for an annual college technology festival.",
    postedBy: { id: "c6", name: "TechFest Committee", role: "Event Organizer", rating: 4.4 }
  },
  {
    id: "p7",
    title: "Landing Page for Startup",
    category: "Web Design",
    budget: 7000,
    experienceLevel: "Intermediate",
    projectType: "Fixed",
    duration: "2 weeks",
    deadline: "2025-02-20",
    datePosted: "2025-01-25",
    skillsRequired: ["UI/UX", "SEO"],
    proposalsCount: 14,
    location: "Remote",
    image: p7,
    shortDescription: "Conversion-focused startup landing page.",
    fullDescription: "Create a visually strong landing page optimized for user engagement and sign-ups.",
    postedBy: { id: "c7", name: "NextWave Labs", role: "Tech Startup", rating: 4.7 }
  },
  {
    id: "p8",
    title: "3D Mascot for App",
    category: "3D Design",
    budget: 9500,
    experienceLevel: "Expert",
    projectType: "Fixed",
    duration: "3 weeks",
    deadline: "2025-03-05",
    datePosted: "2025-01-08",
    skillsRequired: ["Blender", "3D Modeling"],
    proposalsCount: 6,
    location: "Remote",
    image: p8,
    shortDescription: "Custom 3D mascot character design.",
    fullDescription: "Design a unique and expressive 3D mascot for branding and marketing use.",
    postedBy: { id: "c8", name: "Appify", role: "Product Team", rating: 4.8 }
  },
  {
    id: "p9",
    title: "Social Media Ad Creatives",
    category: "Marketing Design",
    budget: 3200,
    experienceLevel: "Beginner",
    projectType: "Fixed",
    duration: "1 week",
    deadline: "2025-02-14",
    datePosted: "2025-01-15",
    skillsRequired: ["Canva", "Photoshop"],
    proposalsCount: 20,
    location: "Remote",
    image: p9,
    shortDescription: "Scroll-stopping Instagram ad creatives.",
    fullDescription: "Design engaging ad creatives for social campaigns targeting Gen-Z audience.",
    postedBy: { id: "c9", name: "Glow Beauty", role: "Marketing Manager", rating: 4.5 }
  },
  {
    id: "p10",
    title: "E-commerce Product Gallery",
    category: "Web Development",
    budget: 6500,
    experienceLevel: "Intermediate",
    projectType: "Hourly",
    duration: "2 weeks",
    deadline: "2025-02-18",
    datePosted: "2025-01-14",
    skillsRequired: ["JavaScript", "React"],
    proposalsCount: 11,
    location: "Remote",
    image: p10,
    shortDescription: "Interactive product gallery system.",
    fullDescription: "Build a dynamic product gallery with zoom, filters and quick preview features.",
    postedBy: { id: "c10", name: "StyleCart", role: "E-commerce Brand", rating: 4.6 }
  },
  {
    id: "p11",
    title: "Brand Guidelines Document",
    category: "Branding",
    budget: 2800,
    experienceLevel: "Intermediate",
    projectType: "Fixed",
    duration: "10 days",
    deadline: "2025-02-22",
    datePosted: "2025-01-22",
    skillsRequired: ["Brand Strategy", "Documentation"],
    proposalsCount: 5,
    location: "Remote",
    image: p11,
    shortDescription: "Detailed brand guidelines PDF.",
    fullDescription: "Prepare a professional brand guidelines document covering logo usage, fonts and colors.",
    postedBy: { id: "c11", name: "LaunchPad", role: "Startup Founder", rating: 4.4 }
  },
  {
    id: "p12",
    title: "Animated Logo for Tech Startup",
    category: "Motion Design",
    budget: 4500,
    experienceLevel: "Intermediate",
    projectType: "Fixed",
    duration: "1 week",
    deadline: "2025-02-25",
    datePosted: "2025-01-30",
    skillsRequired: ["After Effects", "Motion Graphics"],
    proposalsCount: 8,
    location: "Remote",
    image: p12,
    shortDescription: "Smooth animated logo reveal.",
    fullDescription: "Create a dynamic animated logo intro for website and promotional videos.",
    postedBy: { id: "c12", name: "CodeNova", role: "Tech Startup", rating: 4.7 }
  },
  {
    id: "p13",
    title: "Mobile App Icon Set",
    category: "App Design",
    budget: 3800,
    experienceLevel: "Beginner",
    projectType: "Fixed",
    duration: "1 week",
    deadline: "2025-02-27",
    datePosted: "2025-01-28",
    skillsRequired: ["Figma", "Icon Design"],
    proposalsCount: 13,
    location: "Remote",
    image: p13,
    shortDescription: "Custom icon set for productivity app.",
    fullDescription: "Design cohesive and minimal app icon pack following modern UI standards.",
    postedBy: { id: "c13", name: "FocusFlow", role: "App Founder", rating: 4.5 }
  },
  {
    id: "p14",
    title: "Print Ad Campaign Design",
    category: "Marketing Design",
    budget: 7500,
    experienceLevel: "Expert",
    projectType: "Fixed",
    duration: "3 weeks",
    deadline: "2025-03-10",
    datePosted: "2025-01-31",
    skillsRequired: ["Campaign Design", "Print Media"],
    proposalsCount: 4,
    location: "On-site",
    image: p14,
    shortDescription: "Complete print campaign visuals.",
    fullDescription: "Develop a strong visual campaign for lifestyle brand across newspapers and billboards.",
    postedBy: { id: "c14", name: "UrbanLife", role: "Marketing Head", rating: 4.9 }
  },
  {
    id: "p15",
    title: "Digital Art Series",
    category: "Digital Art",
    budget: 4899,
    experienceLevel: "Intermediate",
    projectType: "Fixed",
    duration: "2 weeks",
    deadline: "2025-03-15",
    datePosted: "2025-03-03",
    skillsRequired: ["Procreate", "Illustration"],
    proposalsCount: 6,
    location: "Remote",
    image: p15,
    shortDescription: "Original digital art collection.",
    fullDescription: "Create a themed digital art series for an upcoming online exhibition.",
    postedBy: { id: "c15", name: "ArtSphere", role: "Gallery Curator", rating: 4.6 }
  },
  {
    id: "p16",
    title: "Corporate Identity Package",
    category: "Branding",
    budget: 9999,
    experienceLevel: "Expert",
    projectType: "Fixed",
    duration: "4 weeks",
    deadline: "2025-03-25",
    datePosted: "2025-03-07",
    skillsRequired: ["Brand Identity", "Visual Systems"],
    proposalsCount: 3,
    location: "Hybrid",
    image: p16,
    shortDescription: "Full corporate identity development.",
    fullDescription: "Develop logo, stationery, brand book and corporate communication templates.",
    postedBy: { id: "c16", name: "PrimeCorp", role: "Corporate Client", rating: 4.8 }
  },
  {
    id: "p17",
    title: "Website Redesign for E-commerce Store",
    category: "Web Development",
    budget: 8799,
    experienceLevel: "Intermediate",
    projectType: "Fixed",
    duration: "3 weeks",
    deadline: "2025-03-28",
    datePosted: "2025-03-09",
    skillsRequired: ["React", "UX Optimization"],
    proposalsCount: 10,
    location: "Remote",
    image: p17,
    shortDescription: "Modern redesign of online fashion store.",
    fullDescription: "Redesign website UI to improve user flow, checkout experience and performance.",
    postedBy: { id: "c17", name: "FashionHub", role: "Store Owner", rating: 4.7 }
  },
  {
    id: "p18",
    title: "Product Photography Session",
    category: "Photography",
    budget: 6799,
    experienceLevel: "Intermediate",
    projectType: "Fixed",
    duration: "1 week",
    deadline: "2025-03-18",
    datePosted: "2025-03-04",
    skillsRequired: ["Product Photography", "Lighting"],
    proposalsCount: 5,
    location: "On-site",
    image: p18,
    shortDescription: "Professional product shoot.",
    fullDescription: "Capture high-quality product images for marketing and website use.",
    postedBy: { id: "c18", name: "TechNova", role: "Startup Founder", rating: 4.6 }
  }
];

export const profiles = mockTalents;

export const getAllProjects = () => projects;

>>>>>>> a91243805d08f328402fd2e4be2d22368deee673
